import SwiftUI

/// In-app display of the Terms of Use and Privacy Policy
struct TermsAndPrivacyView: View {
    @Environment(\.colorScheme) private var colorScheme

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {
                // Draft banner
                HStack {
                    Spacer()
                    Label("DRAFT — Pending Legal Review", systemImage: "exclamationmark.triangle.fill")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(.orange)
                        .padding(.horizontal, 16)
                        .padding(.vertical, 8)
                        .background(.orange.opacity(0.1), in: RoundedRectangle(cornerRadius: 8))
                    Spacer()
                }

                // Title
                VStack(alignment: .leading, spacing: 8) {
                    Text("Terms of Use and Privacy Policy")
                        .font(PSDFonts.largeTitle)
                        .foregroundStyle(PSDTheme.headingText(for: colorScheme))
                    Text("Peninsula School District")
                        .font(PSDFonts.title3)
                        .foregroundStyle(.secondary)
                    Text("Last Updated: March 12, 2026")
                        .font(.caption)
                        .foregroundStyle(.tertiary)
                }

                PolicySection(number: "1", title: "Overview") {
                    Text("LessonLens is a voluntary, self-directed professional growth tool developed by Peninsula School District (PSD). It allows teachers to record or import classroom lessons, receive AI-generated coaching feedback aligned to teaching frameworks, and reflect on their practice privately.")
                    Text("LessonLens is not an evaluation tool. It is not used for personnel decisions, performance reviews, or administrative oversight of any kind.")
                }

                PolicySection(number: "2", title: "Who Can Use LessonLens") {
                    Text("LessonLens is available to Peninsula School District staff with an active @psd401.net Google Workspace account. Authentication uses the same district Google account used for all other district services. Access is restricted to the @psd401.net domain and enforced on both the application and server side.")
                }

                PolicySection(number: "3", title: "Voluntary Use") {
                    Text("Use of LessonLens is completely voluntary. No teacher, staff member, or administrator is required to use LessonLens for any purpose. There are no consequences for choosing not to use the application, and no usage data is reported to supervisors, evaluators, or district leadership.")
                }

                PolicySection(number: "4", title: "What Data LessonLens Collects") {
                    PolicySubsection(number: "4.1", title: "Account Information") {
                        Text("When you sign in, LessonLens receives your name, email address, and profile photo from your district Google account. This information is used solely to authenticate your identity and personalize your experience. No additional personal information is collected.")
                    }
                    PolicySubsection(number: "4.2", title: "Recordings") {
                        Text("Audio and video recordings of lessons are stored locally on your device. Audio files are never uploaded to any server. Video files are uploaded to Google's Gemini API for analysis only (see Section 5.2).")
                    }
                    PolicySubsection(number: "4.3", title: "Transcripts") {
                        Text("Audio transcription is performed entirely on your device using an on-device AI model (WhisperKit). Transcripts are stored locally and are only sent to Google's Gemini API when you request an analysis.")
                    }
                    PolicySubsection(number: "4.4", title: "Analysis and Feedback") {
                        Text("AI-generated coaching feedback, technique evaluations, strengths, growth areas, and suggested next steps are generated by Google's Gemini API and stored locally on your device.")
                    }
                    PolicySubsection(number: "4.5", title: "Reflections and Chat") {
                        Text("Self-reflections, self-ratings, and coaching chat conversations are stored locally on your device.")
                    }
                    PolicySubsection(number: "4.6", title: "Usage Settings") {
                        Text("Your preferences (selected teaching framework, technique selections, display settings) are stored locally on your device.")
                    }
                }

                PolicySection(number: "5", title: "How Your Data Is Processed") {
                    PolicySubsection(number: "5.1", title: "On-Device Processing") {
                        Text("The following operations happen entirely on your device and involve no data transmission:")
                        BulletList(items: [
                            "Audio recording",
                            "Audio transcription (WhisperKit on-device model)",
                            "Data storage (Apple SwiftData, local database)",
                            "PDF and Markdown export (generated locally, saved to a location you choose)"
                        ])
                    }
                    PolicySubsection(number: "5.2", title: "Cloud Processing") {
                        Text("The following operations require sending data to Google's Gemini API via a PSD-operated backend server:")
                        Text("Text-based analysis: Your transcript text and selected teaching framework techniques are sent to Google's Gemini API, which returns coaching feedback. The transcript and response are not permanently stored by Google or by the PSD backend server.").bold()
                        Text("Video analysis: Your video file is uploaded directly to Google's Gemini Files API for analysis. The video is automatically deleted from Google immediately after analysis completes. Even in the event of a deletion failure, Google automatically purges uploaded files within 48 hours.").bold()
                        Text("Coaching chat: When you use the coaching chat feature, your transcript summary, analysis summary, and chat message history are sent to Google's Gemini API. No chat history is stored on the PSD backend server.").bold()
                    }
                    PolicySubsection(number: "5.3", title: "PSD Backend Server") {
                        Text("The PSD backend server acts as a stateless proxy between LessonLens and Google's Gemini API. It validates your authentication token, forwards requests, and enforces rate limits. The backend server does not store transcripts, analysis results, chat conversations, recordings, or any personally identifiable session data. Each request is processed independently with no server-side record of prior interactions.")
                    }
                }

                PolicySection(number: "6", title: "Who Can See Your Data") {
                    Text("You are the only person who can see your recordings, transcripts, analyses, reflections, and chat conversations.")
                        .fontWeight(.semibold)
                    BulletList(items: [
                        "No administrator, evaluator, or colleague has access to your sessions.",
                        "The PSD technology team can see aggregate API usage metrics (number of requests, model used, token costs) but cannot see who made the requests or the content of any request or response.",
                        "District technology staff could theoretically determine who has downloaded the application, but cannot determine who is actively using it or what they are doing with it."
                    ])
                }

                PolicySection(number: "7", title: "Data Retention and Deletion") {
                    PolicySubsection(number: "7.1", title: "Local Data") {
                        Text("All teaching session data (recordings, transcripts, analyses, reflections, chat conversations) is stored locally on your device. You may delete any session at any time from within the application. Deleting a session permanently removes the recording file and all associated data (transcript, analysis, reflections, and chat history).")
                    }
                    PolicySubsection(number: "7.2", title: "Cloud Data") {
                        Text("No session data is retained on the PSD backend server. Google's Gemini API processes data in-memory with a maximum 24-hour cache for performance purposes. This cache is stored in RAM only (not on disk), is isolated at the project level, and is automatically purged. Google does not use your data to train AI models.")
                    }
                    PolicySubsection(number: "7.3", title: "Transitory Records") {
                        Text("Under Washington State Office of the Secretary of State guidelines, recordings processed through LessonLens are classified as transitory records. They are created for temporary reference and are not retained as permanent district records.")
                    }
                    PolicySubsection(number: "7.4", title: "Account Data") {
                        Text("Your authentication tokens are stored in your device's macOS Keychain (Apple's secure credential storage). Session tokens expire after 7 days; refresh tokens expire after 30 days. Signing out of LessonLens immediately clears all stored tokens.")
                    }
                }

                PolicySection(number: "8", title: "Third-Party Services") {
                    Text("LessonLens uses the following third-party services:")
                    VStack(alignment: .leading, spacing: 8) {
                        ServiceRow(service: "Google OAuth 2.0", purpose: "Authentication", dataSent: "Standard OAuth flow (no LessonLens data)")
                        ServiceRow(service: "Gemini API (Vertex AI)", purpose: "AI analysis and coaching chat", dataSent: "Transcripts, technique definitions, chat messages")
                        ServiceRow(service: "WhisperKit", purpose: "On-device audio transcription", dataSent: "None (runs locally)")
                    }
                    Text("Google's handling of data sent to the Gemini API via Vertex AI is governed by the Peninsula School District's existing Data Processing Agreement (DPA) with Google, which covers both Google Workspace and Google Cloud/Vertex AI services. This agreement is FERPA and COPPA compliant.")
                    Text("No analytics, telemetry, crash reporting, or usage tracking services are used. LessonLens does not collect or transmit any behavioral or usage data.")
                }

                PolicySection(number: "9", title: "Student Data") {
                    Text("LessonLens is a teacher-facing professional development tool. It is not designed to collect, store, or process student data. However, classroom recordings may incidentally capture student voices or images.")
                    BulletList(items: [
                        "Audio recordings are transcribed on-device and never uploaded to external servers.",
                        "Video recordings sent for analysis are automatically deleted from Google immediately after processing.",
                        "All recordings are classified as transitory records under Washington State guidelines.",
                        "Teachers are responsible for ensuring their use of classroom recordings complies with district policies on classroom recording and any applicable notification requirements."
                    ])
                }

                PolicySection(number: "10", title: "AI-Generated Content Disclaimer") {
                    Text("Coaching feedback, technique evaluations, and chat responses provided by LessonLens are generated by artificial intelligence. This content is intended solely as a tool for personal reflection and professional growth.")
                    Text("AI-generated feedback does not constitute official evaluation, professional guidance, or district endorsement of any teaching practice. It should not be used as the sole basis for instructional decisions. Teachers are encouraged to use AI feedback as one input among many in their professional development, alongside peer collaboration, mentorship, and formal professional learning.")
                }

                PolicySection(number: "11", title: "Data Security") {
                    BulletList(items: [
                        "Local data is stored using Apple's SwiftData framework within the application's sandboxed storage.",
                        "Authentication credentials are stored in the macOS Keychain, Apple's secure credential management system.",
                        "All communication between LessonLens and the PSD backend server uses HTTPS encryption.",
                        "All communication between the PSD backend server and Google's Gemini API uses HTTPS encryption.",
                        "The PSD backend server is hosted on Google Cloud Run within the district's Google Cloud project.",
                        "Access to the backend server's API requires a valid authentication token from a @psd401.net account."
                    ])
                }

                PolicySection(number: "12", title: "Changes to This Policy") {
                    Text("This policy may be updated as LessonLens evolves. Users will be notified of material changes through the application. Continued use of LessonLens after changes are posted constitutes acceptance of the updated terms.")
                }

                PolicySection(number: "13", title: "Contact") {
                    Text("For questions about this policy or LessonLens, contact the Department of Research & Assessment at Peninsula School District.")
                }
            }
            .padding(24)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
        .psdPageBackground()
    }
}

// MARK: - Policy Section

private struct PolicySection<Content: View>: View {
    let number: String
    let title: String
    @ViewBuilder let content: Content

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("\(number). \(title)")
                .font(PSDFonts.headline)
                .foregroundStyle(PSDTheme.accent)
            VStack(alignment: .leading, spacing: 8) {
                content
            }
            .font(.subheadline)
        }
    }
}

// MARK: - Policy Subsection

private struct PolicySubsection<Content: View>: View {
    let number: String
    let title: String
    @ViewBuilder let content: Content

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text("\(number) \(title)")
                .font(.subheadline.weight(.semibold))
            VStack(alignment: .leading, spacing: 6) {
                content
            }
            .font(.subheadline)
        }
        .padding(.leading, 8)
    }
}

// MARK: - Bullet List

private struct BulletList: View {
    let items: [String]

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            ForEach(items, id: \.self) { item in
                HStack(alignment: .top, spacing: 8) {
                    Text("\u{2022}")
                        .foregroundStyle(.secondary)
                    Text(item)
                }
            }
        }
        .padding(.leading, 8)
    }
}

// MARK: - Service Row

private struct ServiceRow: View {
    let service: String
    let purpose: String
    let dataSent: String

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(service).fontWeight(.medium)
            Text("Purpose: \(purpose)").foregroundStyle(.secondary)
            Text("Data sent: \(dataSent)").foregroundStyle(.secondary)
        }
        .padding(8)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(.regularMaterial, in: RoundedRectangle(cornerRadius: 6))
    }
}

#Preview {
    TermsAndPrivacyView()
}
